### PR TITLE
Fix #208

### LINKED ISSUE #208: Add transformation dropdown menu on downloads page
Users should have the following transformation options:

- No transformation
- Z-score (`STANDARD`)
- [0,1] (`MINMAX`)

### PR DESCRIPTION
**Pull request by Willv19**
## Issue Number

#208

## Purpose/Implementation Notes

I added a transformation options dropdown in the download page, and connect it to Redux everywhere that the aggregation option already is. I also added a help icon after the label for each dropdown, but the link needs to be replaced once the docs are online.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

* [ ] Bugfix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Functional tests

I ran the frontend locally against a local API copy with the code of the backend PR.

## Checklist

_Put an `x` in the boxes that apply._

* [x] Lint and unit tests pass locally with my changes
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] I have added necessary documentation (if appropriate)
* [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

2018-08-01-14 50 03-screenshot
2018-08-01-14 50 07-screenshot

### CODE REVIEW

**Comment by dvenprasad** [comment]
@jaclyn-taroni Scientifically, which is term is more widespread?

**Comment by jaclyn-taroni** [comment]
Ah, I bet it depends on the community, but I imagine the users that would recognize min max would also understand zero to one for example

**Comment by dvenprasad** [comment]
Okay, I'm okay with z-score and zero to one as the values for the dropdown.

**Comment by Willv19** [comment]
Here are the new dropdowns:
2018-08-02-09 54 50-screenshot
2018-08-02-09 54 53-screenshot

**Pull request merged**
