### PR TITLE
Fix #200

### LINKED ISSUE #200: Link the PubMed ID/ Publication Title to the publication
Copying over from https://github.com/AlexsLemonade/refinebio/issues/440 where @Miserlou noted this as a front end issue

### Context

Results from usability evals

### Problem or idea

Users mentioned on multiple occasions that they would like to be linked to the publication when looking at the publication title or PubMed ID. 

This was briefly discussed during the search page iteration. It was suggested that we look up the publication via pubmed API. 

### Solution or next step

Solution described [here](
https://github.com/AlexsLemonade/refinebio/issues/440#issuecomment-407472330)

> I think this is really a frontend issue since it'll just be a link to `https://www.ncbi.nlm.nih.gov/pubmed/?term={{experiment.pubmed_id}}`

#### Related

#151, https://github.com/AlexsLemonade/refinebio/issues/439

### PR DESCRIPTION
**Pull request by Willv19**
## Issue Number

#200 

## Purpose/Implementation Notes

The "Pubmed ID" field in the submitter supplied information is now a link to the associated pubmed page.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

* [ ] Bugfix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Functional tests

I ran the frontend locally.

## Checklist

_Put an `x` in the boxes that apply._

* [x] Lint and unit tests pass locally with my changes
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] I have added necessary documentation (if appropriate)
* [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots
Sequence of events:
2018-07-30-15 04 08-screenshot
2018-07-30-15 04 14-screenshot

### CODE REVIEW

**Comment by dvenprasad** [comment]
What about cases when there is a publication title present? Are the publication title fields also linked?

**Comment by Miserlou** [comment]
Agreed, this should also link the title if possible. Technically speaking this is good though.

**Comment by Miserlou** [comment]
We have the complete authors list now (once the PR lands), we could also consider linking author name to a refine.bio search for that name.

**Comment by Willv19** [comment]
New authors page:
2018-08-07-14 52 25-screenshot
After clicking the first author link:
2018-08-07-14 52 30-screenshot

**Comment by Miserlou** [comment]
Looks good, you might as well do the institution while you're at it

**Comment by Willv19** [comment]
Link:
2018-08-07-15 03 40-screenshot
After clicking link:
2018-08-07-15 03 44-screenshot

**Pull request merged**
