### PR TITLE
Add horizontal scrolling buttons

### LINKED ISSUE #152: No Way to Scroll Horizontally in Wide Samples Detail List
For an experiment with detailed samples information, lots of the details are buried in a frame which cannot be scrolled horizontally.

I can scroll right by middle-clicking and scrolling right, but I wouldn't do this if I didn't know that information wasn't there. Also, it's just a horrible interaction.

Ex: https://staging.refine.bio/experiments/2?ref=search

screen shot 2018-07-16 at 10 32 35 am
screen shot 2018-07-16 at 10 32 39 am

### PR DESCRIPTION
**Pull request by Willv19**
## Issue Number

Fixes #152 

## Purpose/Implementation Notes

Add buttons on either side of the menu that scroll over on click. The new dependency is a polyfill for smooth scrolling support in javascript so the table smoothly scrolls when the button is pressed instead of teleporting to the new location.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

* [ ] Bugfix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Functional tests

I ran the frontend locally.

## Checklist

_Put an `x` in the boxes that apply._

* [x] Lint and unit tests pass locally with my changes
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] I have added necessary documentation (if appropriate)
* [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots
Scrolling on the samples page:
2018-08-06-13 50 32-screenshot
2018-08-06-13 50 37-screenshot
2018-08-06-13 50 41-screenshot
Scrolling on a modal:
2018-08-06-13 51 45-screenshot
2018-08-06-13 51 48-screenshot
2018-08-06-13 51 50-screenshot
Disabled on the samples page:
2018-08-06-13 51 56-screenshot
Disabled on a modal:
2018-08-06-13 50 58-screenshot

### CODE REVIEW

**Comment by Miserlou** [comment]
Buttons appear but are deactivated and have a deactivated mouse hover-state for me.

**Comment by Willv19** [comment]
That's the expected behaviour when there is no need to scroll horizontally. Only some of the tables are wider than the table view.

**Comment by Miserlou** [comment]
Documenting: I thought the buttons were for tabbing the page at first.

Suggest we don't display them at all, except in the direction that they are able to scroll, if any. 

Resizing a column also makes them usable, but does not change the state color. (May be a superfluous bug since we probably shouldn't ever show the greyed out once.)

**Comment by Willv19** [comment]
Now the buttons disappear when not needed.

Disabled:
2018-08-06-14 48 44-screenshot
Scrolling:
2018-08-06-14 49 00-screenshot
2018-08-06-14 49 03-screenshot
2018-08-06-14 49 04-screenshot
2018-08-06-14 49 06-screenshot
2018-08-06-14 49 07-screenshot
2018-08-06-14 49 09-screenshot

**Comment by Willv19** [comment]
It looks like table resizes still don't update the button states. I have to keep looking into that.

**Pull request merged**
