### PR TITLE
New feature: "Clear dataset" button

### PR DESCRIPTION
**Pull request by dongbohu**
## Issue Number
#102

## Purpose/Implementation Notes

* A new button that will clear the whole dataset
* Disable `has publication` filter when its counter is 0.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

* [x] Bugfix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

* [ ] Lint and unit tests pass locally with my changes
* [x] I have added tests that prove my fix is effective or that my feature works
* [ ] I have added necessary documentation (if appropriate)
* [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots
See the demo page on my local desktop:
http://165.123.67.202:3000/results?q=neuro

### CODE REVIEW

**Comment by Willv19** [comment]
It looks like there is an issue with the navbar CSS and the buttons:
2018-07-24-15 04 36-screenshot
If I am not mistaken, this should be fixed by my latest PR, which fixed the issue of navbar `li`s not having the same width as their children. Try merging from dev and seeing if the style issue is still there.

Other than that, it looks good to me.

**Comment by dongbohu** [comment]
@Willv19: The "clear" button" does l;ook much better with the latest code in `dev`. Thanks.  

@Miserlou or @Willv19: If you don't have any other comments, can you approve this PR so that I can merge it? Thanks.

**Comment by dongbohu** [comment]
@Willv19 and @Miserlou: @dvenprasad and I had a short discussion about whether it will be better to move this `Clear` button to `Download` page. Let's keep this PR open for now before we decide which place will be better. Thanks.

**Comment by Miserlou** [comment]
Confirming the CSS issue:

screen shot 2018-07-25 at 10 56 02 am

Looks like the functionality is there though. 

I think in it's current positioning, it is too easy to click and erase all work. I suggest that we either/or/both - moving from `[Download] [Clear]` to `[Clear] [Download]`, and adding a confirmation dialog box before we actually clear the dataset. This is probably a Deepa question.

**Comment by dongbohu** [comment]
I talked to @cgreene briefly about the location of this button. I am going to move the button to `Doadload` page for now. We can decide whether this is the best choice after some user interviews later.

**Comment by dongbohu** [comment]
@Miserlou, @Willv19 and @dvenprasad: I have updated the code, which has the `Remove Dataset` button on `Download` page. See the demo here:
http://165.123.67.202:3000/results?q=neuro
Just add some samples then click `Download` button on the header. Right now the button is located on the right side of `Share Dataset` button.

**Comment by Miserlou** [comment]
Alright!

screen shot 2018-07-26 at 3 45 41 pm

It looks like the spacing is off on my view, the Remove button is kind of floating in the center, should the have the same spacing as the pair on the right?

I'd also suggest that we change this from [Yes] [Cancel] to  [ No, Keep This Dataset] [Yes, Clear Dataset]
screen shot 2018-07-26 at 3 45 46 pm

**Comment by Miserlou** [comment]
Functionality is great though, I'm happy we have this now.

**Comment by dongbohu** [comment]
@Miserlou: I have changed texts on both buttons. About the space between `Share Dataset` and `Remove Dataset` buttons, I tried a few classes, but they all put the two buttons shoulder by shoulder w/o any space, like this: 
screenshot from 2018-07-26 17-03-21

I actually prefer a larger space between the two buttons, because it makes the two buttons more distinct.

**Comment by cgreene** [comment]
I'd ask @dvenprasad to weigh in.

**Comment by dvenprasad** [comment]
Linking this comment from [#102](https://github.com/AlexsLemonade/refinebio-frontend/issues/102#issuecomment-408211101) here since it make sense to address it here.

In terms of what the users can see, removing all samples is equivalent to clearing the dataset.
Based on my understanding of our user's mental modeI, I think even if there's a 'remove dataset' button on top, most of the users will scroll down to look at the samples anyway. I also don't think that users will clear their dataset as often. Given that we currently have brakes (confirmation pop-up) and no mechanism for recovery, it should be with samples to minimize the likelihood of accidents.

**Comment by dongbohu** [comment]
Okay, let me move the button to `Samples` section.

**Comment by dongbohu** [comment]
@dvenprasad, @Miserlou and @Willv19: I have moved the `Remove All` button to `Samples` section of the `Download` page. See the demo page: http://165.123.67.202:3000/results?q=neuro
and this screenshot:
screenshot from 2018-07-27 11-52-48

As you can see, this is not the exact location that @dvenprasad specified earlier. The main reason is because the two tabs `Species View / Experiments View` and the samples table after them are an integrated component, so it is not easy to insert a separate button between them. I tried a few CSS options but they didn't work, so I gave up.

**Comment by Willv19** [comment]
I like the placement, but I think the wording in the confirmation dialogue is a little bit clunky, and it might seem odd to someone who is using the website that is not clear on our concept of a 'dataset'. @dvenprasad what do you think of the wording?

**Comment by dongbohu** [comment]
@Willv19 Good point. I forgot to modify the texts on both buttons after moving the location. Since they are now in `Samples` section, maybe change them to: `Yes, remove all samples` and "No, keep all samples`?

**Comment by dongbohu** [comment]
I changed the wording a little bit. Please check out the demo page again.

**Comment by Willv19** [comment]
LGTM

**Comment by dvenprasad** [comment]
@dongbohu  That button placement is okay. I checked the padding on the button it says it's 4 x 24 but it look definitely looks bigger than that. It has a line height of 1.5 which is also. Do you think there's anything else that could be affecting this?

**Comment by dongbohu** [comment]
@dvenprasad: Let me dig deeper to see why the new button looks bigger.

**Comment by dongbohu** [comment]
@dvenprasad: How do you like the button now?
http://165.123.67.202:3000/results?q=neuro

**Comment by dvenprasad** [comment]
Looks good! 😄

**Pull request merged**
