### PR TITLE
Sample table styles in Experiments page

### LINKED ISSUE #21: Experiment page: Add styles for table component
## Description
Work with @dvenprasad to customize the Table component styles to our liking.

### PR DESCRIPTION
**Pull request by arielsvn**
## Issue Number

closes #21 

## Purpose/Implementation Notes

Added Styles for the Table in the experiments page. We'll still have to decide the content and the columns in #23 

**The changes in this PR depend on the ones in #29.** This PR will only contain the styles for the table after #29 gets merged.

## Types of changes

* [ ] Bugfix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Functional tests

- Pagination of the table
- Changing Table page size
- Sorting columns

## Screenshots

samples table

### CODE REVIEW

**Comment by Miserlou** [comment]
`id` is really just an internal pk, I don't think we want to display that when we have a perfectly good title field.

**Comment by ramenhog** [comment]
@arielsvn do you want to try resolving the merge conflicts before I review this?

**Comment by arielsvn** [comment]
No worries, I'll create a different PR and let you know. I thought once #29 was merged that those commits would be removed from here.

**Comment by cgreene** [comment]
Can you just pull the current master over here?

**Comment by ramenhog** [comment]
Yeah, you should be able to, you'll just need to resolve the conflicts that occur with merging `dev` into this branch

**Comment by arielsvn** [comment]
Yep that solved it, thanks @ramenhog @cgreene! This is ready to be reviewed now.

I was in the process of creating a new PR, and cherry-picking the commit I needed...

**Pull request merged**
