### PR TITLE
Arielsvn/648 useloader fix

### PR DESCRIPTION
**Pull request by arielsvn**
## Issue Number

#648 

## Purpose/Implementation Notes

Another attempt to fixing `useLoader`. [Found a way](https://overreacted.io/a-complete-guide-to-useeffect/#why-usereducer-is-the-cheat-mode-of-hooks) to remove `state` as a dependency from the effect that called `fetch` so that we can avoid the infinite cycles that caused #648 

## Types of changes

* [x] Bugfix (non-breaking change which fixes an issue)

## Functional tests

Added tests for this.

## Checklist

* [x] Lint and unit tests pass locally with my changes
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] I have added necessary documentation (if appropriate)
* [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by davidsmejia** [comment]
I think this is the right idea. It's way cleaner anyway. If you want to stop the infinite loops (you probably do) you can add a React.useCallback on Dashboard/index.js but, IMO it's not the prettiest implementation.

https://github.com/davidsmejia/refinebio-frontend/commit/1a529c33fb0bdf32a24f14b9bf14ef516753feff

**Comment by arielsvn** [comment]
> If you want to stop the infinite loops (you probably do) you can add a React.useCallback on Dashboard/index.js but, IMO it's not the prettiest implementation.

Good catch! I'll try to debug this tomorrow to see why it happened. Thanks for taking a look!

In https://github.com/davidsmejia/refinebio-frontend/commit/1a529c33fb0bdf32a24f14b9bf14ef516753feff one test did not pass.

**Comment by davidsmejia** [comment]
Hey that test fails because in https://github.com/davidsmejia/refinebio-frontend/commit/1a529c33fb0bdf32a24f14b9bf14ef516753feff because in this implementation of useLoader the dependency is the callback itself not the [param] that is redefined it is the function passed to the hook (which is why if we add a useCallback hook it will keep the same function ref and not be redefined) - this is because the Dashboard is reinitialized when that value is changed.

It looks like /dashboard renders 4 times on load before user interaction, 3 on initial load and again when the useLoader gets its ajax call returned, meanwhile, /search loads 3 initial times as well. I'm looking into that now.

**Comment by arielsvn** [comment]
Added `React.useCallback` in the dashboard as suggested by @davidsmejia, that seems to fix the infinite loop in the dashboard.

**Comment by davidsmejia** [comment]
For what it's worth, I think this looks great. Silencing the eslinter seems appropriate too as there is no way to statically apply the dependencies in the useLoader scope.

As for the multiple render calls also seem unavoidable as they are a consequence of the useLoader setting state causing React to do a diff it's not actually rendering anything to screen.

**Comment by arielsvn** [comment]
>  Silencing the eslinter seems appropriate too as there is no way to statically apply the dependencies in the useLoader scope.

Good call, just made the change. Thanks again for keeping an eye on this! Let's get it merged.

@kurtwheeler this should be good to go, can you help us with an 👍 ?

**Pull request merged**
