### PR TITLE
Fix #111

### LINKED ISSUE #111: No Jump to Page Button in Modal
screen shot 2018-07-05 at 6 25 29 pm

In the download page modal, there is an input to jump to a different page, but no button to make it happen. It works with the Enter key.

### PR DESCRIPTION
**Pull request by Willv19**
## Issue Number

#111 

## Purpose/Implementation Notes

Add a "Jump to Page" button on the modal.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

* [x] Bugfix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Functional tests

I ran the frontend locally.

## Checklist

_Put an `x` in the boxes that apply._

* [x] Lint and unit tests pass locally with my changes
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] I have added necessary documentation (if appropriate)
* [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

2018-07-30-10 14 36-screenshot

### CODE REVIEW

**Comment by Willv19** [comment]
I'm not sure about the current styling on the jump button, maybe someone else has a better idea. Another option would be to automatically update which page is displayed when the input is changed.

**Comment by jaclyn-taroni** [comment]
@dvenprasad

**Comment by dvenprasad** [comment]
@Willv19 Use the ghost/Secondary button.

**Comment by Willv19** [comment]
This is the updated look:
2018-07-31-12 48 38-screenshot

I'm afraid it comes with more use of the inline style tag. Without it the elements don't line up well next to each other, and the changes made apply only to this one specific layout.

**Pull request merged**
