### PR TITLE
Add CTA to all add buttons

### LINKED ISSUE #197: Search Page Samples Added Counter is Wrong
On my branch for the CTA issue:
2018-07-27-10 05 50-screenshot

It should say "1 sample added to dataset" at the top.

### PR DESCRIPTION
**Pull request by Willv19**
## Issue Number

Fixes #197 and #130 

## Purpose/Implementation Notes

I added a CTA to all add buttons when a subset of the samples are already in the dataset. Also, I fixed the calculation on the results page for how many samples are in the dataset from that page.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

* [x] Bugfix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Functional tests

I ran the frontend locally

## Checklist

_Put an `x` in the boxes that apply._

* [x] Lint and unit tests pass locally with my changes
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] I have added necessary documentation (if appropriate)
* [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

2018-07-27-10 45 14-screenshot
2018-07-27-10 45 24-screenshot

### CODE REVIEW

**Comment by dvenprasad** [comment]
The 'Add Remaining' button needs to be a ghost button.

Mockup:
screen shot 2018-07-27 at 10 59 22 am

**Comment by Miserlou** [comment]
This is good, I like these buttons a lot more!

I was able to get it into a state where there are two of the same button button on the search page, I'm not sure if this is the intended behavior or not:

**Comment by Miserlou** [comment]
I was able to generate a crash on the download page:

screen shot 2018-07-27 at 11 12 16 am

And there are add buttons on my dataset preview page:
screen shot 2018-07-27 at 11 13 32 am

Clicking them causes the crash

**Comment by Willv19** [comment]
2018-07-27-11 21 51-screenshot

**Comment by dvenprasad** [comment]
- The add buttons in the table are supposed to be ghost buttons
- It's overkill having how many samples are added on a per page basis. Also, the CTA there is ambiguous. Am I adding all samples or only samples on the page?  I would revert back to original CTA 'Add Page to Dataset' without the information block(i.e X samples already in dataset).  Ideally, the users should be able use the sort on the add/remove column to get look at the added samples.

**Comment by Willv19** [comment]
Is this how it should look?
2018-07-31-12 07 51-screenshot

**Comment by dvenprasad** [comment]
Yep, looks good!

**Comment by Miserlou** [comment]
I am still able to repro the crash by removing a sample, reloading the downloading page, then pressing 'Add' on the view samples view.

**Comment by Willv19** [comment]
I agree that it's a problem, but I was also able to reproduce the same crash on the staging server, so it can't be something added by this PR. We should probably file a separate ticket for it.

**Comment by Miserlou** [comment]
Ah, okay. Will file a ticket and approve this.

**Pull request merged**
