### PR TITLE
Use numbers from stats cache in about page

### PR DESCRIPTION
**Pull request by arielsvn**
## Issue Number

close AlexsLemonade/refinebio-frontend#759
close https://github.com/AlexsLemonade/refinebio/issues/1604
close AlexsLemonade/refinebio-frontend#320

## Purpose/Implementation Notes

Change the wording in the about page and starts using actual numbers for the stats we report there.

https://github.com/AlexsLemonade/refinebio/pull/1620 should be deployed before this PR.

@dvenprasad I used [this design](https://projects.invisionapp.com/d/main#/console/13557531/314342370/preview) as guidance. Is the wording alright?

@davidsmejia you can ignore the changes in `src/apiData.json` when reviewing, seems like the file was formatted automatically when I committed it. Only lines 4-9 were added.

## Types of changes

* [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Functional tests

Tested locally.

## Checklist

* [x] Lint and unit tests pass locally with my changes
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] I have added necessary documentation (if appropriate)
* [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

image

### CODE REVIEW

**Comment by cgreene** [comment]
I'm not sure what "raw processed data" is, but I think the stat we were going for is the total size of the original files - not the processed ones.

**Comment by dvenprasad** [comment]
Um...It's `raw data processed` as is we've processed X amount of raw data.

**Comment by cgreene** [comment]
🤦‍♂  Then I'd say the numbers seem low but the copy seems accurate. 😂

**Comment by arielsvn** [comment]
> 🤦‍♂ Then I'd say the numbers seem low but the copy seems accurate. 😂

@cgreene  Yes, those aren't the real numbers. Just dummy ones that I added to test it. The real ones will appear once https://github.com/AlexsLemonade/refinebio/pull/1620 is deployed.

**Pull request merged**
